# Generated by Django 6.0 on 2025-12-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features_alter_servico_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='imagem',
        ),
    ]
